### ISSUE TITLE
Hey! Wanna join a family of JS code golfers?

### ISSUE THREAD

**Issue by xem** [pcaisse/connect-fore#1]
Hello and congrats for your connect four golfing article!

I'm super impressed because I also golfed a 2-player connect four a few years ago.

(it was actually a collection of 4 games golfed in 1kb for js1k 2014: http://js1k.com/2014-dragons/demo/1933)

Anyway, I'm here to invite you to a slack room dedicated to JS code golfing. We're about 80 golfers and the chat is quite active, with new projects appearing regularly.

You can join here if you want: http://register.jsgolf.club

you can also find a list of all our golfed projects and blogs here: https://gist.github.com/xem/206db44adbdd09bac424

Cheers!

**Comment by pcaisse** [comment]
@xem Cool, thanks! I'll check it out!
